import { Inter } from "next/font/google";
import Authprovider from "@/component/Authprovider";
import 'tailwindcss/tailwind.css'
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Authprovider>{children}</Authprovider>
      </body>
    </html>
  );
}
