import { Inter } from "next/font/google";
import Authprovider from "@/component/Authprovider";
import "tailwindcss/tailwind.css";
import { ThemeProvider } from "@/component/theme-provider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Custom ChatGPT",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Authprovider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </Authprovider>
      </body>
    </html>
  );
}
